package io.github.seggan.feg.compiler

enum class Operator(val symbol: String) {
    NOT("!"),
    TODO_1("#"),
    TODO_2("$"),
    MOD("%"),
    AND("&"),
    TODO_3("'"),
    MUL("*"),
    PLUS("+"),
    PRINT(","),
    MINUS("-"),
    DIV("/"),
    TODO_4(":"),
    LESS_THAN("<"),
    EQUAL("="),
    GREATER_THAN(">"),
    INPUT("?"),
    TODO_5("@"),
    ALL("A"),
    TODO_6("B"),
    CHR_ORD("C"),
    TODO_7("D"),
    TODO_8("E"),
    // F is filter
    TODO_9("G"),
    TODO_10("H"),
    TODO_11("I"),
    TODO_12("J"),
    TODO_13("K"),
    LENGTH("L"),
    // M is map
    TODO_14("N"),
    TODO_15("O"),
    TODO_16("P"),
    TODO_17("Q"),
    TODO_18("R"),
    TODO_19("S"),
    TODO_20("T"),
    TODO_21("U"),
    TODO_22("V"),
    TODO_23("W"),
    TODO_24("X"),
    TODO_25("Y"),
    TODO_26("Z"),
    TODO_27("["),
    TODO_28("\\"),
    TODO_29("]"),
    POWER("^"),
    TODO_30("_"),
    ANY("a"),
    TODO_31("b"),
    // c is a digraph char
    TODO_32("d"),
    TODO_33("e"),
    TODO_34("f"),
    TODO_35("g"),
    TODO_36("h"),
    TODO_37("i"),
    TODO_38("j"),
    TODO_39("k"),
    TODO_40("l"),
    // m is a digraph char
    TODO_41("n"),
    TODO_42("o"),
    TODO_43("p"),
    TODO_44("q"),
    // r is a digraph char
    TODO_45("s"),
    TODO_46("t"),
    TODO_47("u"),
    TODO_48("v"),
    TODO_49("w"),
    TODO_50("x"),
    TODO_51("y"),
    TODO_52("z"),
    TODO_53("{"),
    OR("|"),
    TODO_54("}"),
    TODO_55("~")
}